#
# https://github.com/dustin10/VichUploaderBundle/blob/master/docs/usage.md
#
vich_uploader:
    db_driver: orm

    mappings:
        stations:
            uri_prefix: /logos
            upload_destination: '%kernel.project_dir%/public/logos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
