version: "2"

services:

  webserver:
    container_name: piradio
    build:
      context: .
    image: piradio:latest
    environment:
      - APP_ENV=prod
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - "piradio.db:/var/www/html/database.db"
    devices:
      - /dev/snd
