version: "2"

services:

  webserver:
    container_name: piradio
    build:
      context: .
    image: piradio:latest
    environment:
      - APP_ENV=prod
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - "database:/var/www/html/var/database/"
    devices:
      - /dev/snd

volumes:
  database:
